[package]
name = "nimotsu"
version = "0.1.0"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
subtle = "2.4"
rand = "0.8.3"

[dev-dependencies]
proptest = "1.0.0"
